name: dart_randomx
description: Dart wrapper for RandomX proof-of-work (PoW) algorithm.
version: 1.0.2
homepage: https://github.com/gmpassos/dart_randomx

environment:
  sdk: '>=2.13.0 <3.0.0'

executables:
  dart_randomx:

dependencies:
  path: ^1.8.0
  ffi: ^1.1.2
  base_codecs: ^1.0.1
  collection: ^1.15.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
