name: dart_randomx
description: Dart wrapper for RandomX proof-of-work (PoW) algorithm.
version: 1.0.0
homepage: https://github.com/gmpassos/dart_randomx

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  path: ^1.8.0
  ffi: ^1.1.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
